name: 'Contrast AI SmartFix'
description: 'Automatically generate fixes for vulnerabilities detected by Contrast Security'
author: 'Contrast Security'

branding:
  icon: 'shield'
  color: 'green'

inputs:
  build_command:
    description: 'Command to build the application'
    required: false
  max_qa_attempts:
    description: 'Maximum number of QA intervention attempts'
    required: false
    default: '6'
  formatting_command:
    description: 'Command to format code (optional)'
    required: false
  max_open_prs:
    description: 'Maximum number of open PRs'
    required: false
    default: '5'
  max_events_per_agent:
    description: 'Maximum number of events per agent run before terminating (default: 120)'
    required: false
    default: '120'
  github_token:
    description: 'GitHub token for PR operations'
    required: true
  base_branch:
    description: 'Base branch for PRs'
    required: false
    default: '${{ github.event.repository.default_branch }}'
  contrast_host:
    description: 'Contrast Security API host'
    required: true
  contrast_org_id:
    description: 'Contrast Organization ID'
    required: true
  contrast_app_id:
    description: 'Contrast Application ID'
    required: true
  contrast_authorization_key:
    description: 'Contrast Authorization Key'
    required: true
  contrast_api_key:
    description: 'Contrast API Key'
    required: true
  gemini_api_key:
    description: 'Gemini API key for Google AI Studio'
    required: false
  anthropic_api_key:
    description: 'Anthropic API key'
    required: false
  aws_bearer_token_bedrock:
    description: 'AWS Bedrock API Bearer Token (alternative to AWS IAM credentials)'
    required: false
  aws_region:
    description: 'AWS Region for Bedrock (required when using aws_bearer_token_bedrock)'
    required: false
  azure_api_key:
    description: 'Azure API Key for Azure OpenAI'
    required: false
  azure_api_base:
    description: 'Azure API Base URL'
    required: false
  azure_api_version:
    description: 'Azure API Version'
    required: false
  agent_model:
    description: 'LLM model path to use for the agent'
    required: false
  skip_writing_security_test:
    description: 'Whether to attempt writing security tests'
    required: false
    default: 'false'
  skip_qa_review:
    description: 'Whether to skip QA review'
    required: false
    default: 'false'
  debug_mode:
    description: 'Enable debug mode for verbose logging'
    required: false
    default: 'false'
  vulnerability_severities:
    description: 'Array of vulnerability severity levels to process (allowed: CRITICAL, HIGH, MEDIUM, LOW, NOTE)'
    required: false
    default: '["CRITICAL", "HIGH"]'
  run_task:
    description: 'Specifies the task for the action to perform. "generate_fix" (default) runs main.py, "merge" runs merge_handler.py.'
    required: false
    default: 'generate_fix'
  enable_full_telemetry:
    description: 'Enable full telemetry, including potentially sensitive data. Defaults to true.'
    required: false
    default: 'true'
  coding_agent:
    description: 'Specifies the coding agent to use for generating fixes. Allowed values: SMARTFIX, GITHUB_COPILOT, CLAUDE_CODE.'
    required: false
    default: 'SMARTFIX'
  use_contrast_llm:
    description: 'Use Contrast LLM as your default LLM provider. Set to false if using your own LLM.'
    required: false
    default: 'false'
  enable_anthropic_prompt_caching:
    description: 'Enable Anthropic prompt caching for supported models (bedrock/claude and anthropic/claude). Defaults to true.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    # Main header to clearly mark the beginning of the action (Linux/macOS)
    - name: Begin SmartFix Process
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo ""
        echo "================================================================"
        echo "ðŸ›¡ï¸  CONTRAST AI SMARTFIX PROCESS STARTED"
        echo "================================================================"
        echo ""

    # Main header to clearly mark the beginning of the action (Windows)
    - name: Begin SmartFix Process (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        @echo off
        echo.
        echo ================================================================
        echo ðŸ›¡ï¸  CONTRAST AI SMARTFIX PROCESS STARTED
        echo ================================================================
        echo.

    # Verify Git is available (Linux/macOS)
    - name: Verify Git availability
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo "Verifying Git availability..."
        which git || { echo "ERROR: Git not found. Git is required for this action."; exit 1; }
        echo "Git version: $(git --version)"

    # Verify Git is available and ensure Git Bash is in PATH (Windows)
    - name: Verify Git availability (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        @echo off

        echo Verifying Git availability...
        where git >nul 2>nul
        if %ERRORLEVEL% NEQ 0 (
          echo ERROR: Git not found. Git is required for this action.
          exit /b 1
        )

        echo Git version:
        git --version

        rem Add standard Git paths to PATH if they exist
        if exist "C:\Program Files\Git\bin" (
          echo Adding Git Bash bin directory to PATH...
          set "PATH=%PATH%;C:\Program Files\Git\bin"
        )

        if exist "C:\Program Files\Git\cmd" (
          echo Adding Git cmd directory to PATH...
          set "PATH=%PATH%;C:\Program Files\Git\cmd"
        )

        rem Verify bash.exe is available
        where bash.exe >nul 2>nul
        if %ERRORLEVEL% NEQ 0 (
          echo ERROR: bash.exe not found in PATH after adding Git directories.
          echo Git Bash is required for this action to function properly.
          exit /b 1
        ) else (
          echo Git Bash is available in PATH
        )

        echo Git verification completed successfully

    # Checkout with reduced verbosity
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Setup tools section with cleaner output
    - name: Environment setup header
      shell: bash
      run: |
        echo ""
        echo "================================================================"
        echo "ðŸ”§ ENVIRONMENT SETUP"
        echo "================================================================"
        echo ""

    # Reduce Python setup verbosity
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Install uv tool for dependency management
    - name: Install uv
      shell: bash
      run: |
        echo ""
        echo "ðŸ“¦ Installing uv package manager..."
        if [ "$RUNNER_OS" = "Windows" ]; then
          pip install uv==0.7.15 > uv-install.log || (cat uv-install.log && exit 1)
        else
          pip install uv==0.7.15 > /tmp/uv-install.log || (cat /tmp/uv-install.log && exit 1)
        fi
        echo "âœ… uv installed successfully"

    # Install dependencies using uv (Linux/macOS)
    - name: Install dependencies with uv
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo ""
        echo "ðŸ“¦ Installing Python packages using uv..."
        echo "ðŸ“Ž Using lockfile for deterministic installation"
        uv pip sync --system ${{ github.action_path }}/src/requirements.lock > /tmp/uv-output.log || (cat /tmp/uv-output.log && exit 1)
        echo "âœ… Python dependencies installed successfully"

    # Install dependencies using uv (Windows)
    - name: Install dependencies with uv (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo.
        echo ðŸ“¦ Installing Python packages using uv...
        echo ðŸ“Ž Using lockfile for deterministic installation

        rem Convert forward slashes to backslashes for Windows path
        set "REQUIREMENTS_PATH=%GITHUB_ACTION_PATH%\src\requirements.lock"

        uv pip sync --system "%REQUIREMENTS_PATH%" > uv-output.log || (type uv-output.log && exit /b 1)
        echo âœ… Python dependencies installed successfully

    # Reduce Node.js setup verbosity
    - name: Set up Node.js
      shell: bash
      run: |
        echo ""
        echo "âž¡ï¸ Setting up Node.js 22..."

    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        check-latest: false

    # Install GitHub CLI (Linux/macOS)
    - name: Install GitHub CLI
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo ""
        echo "ðŸ“¦ Installing GitHub CLI..."
        # Check if GitHub CLI is already installed
        if command -v gh &> /dev/null; then
          echo "âœ… GitHub CLI is already installed"
          gh --version
        else
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update -qq > /dev/null
            sudo apt-get install -y -qq gh > /dev/null
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install gh || echo "GitHub CLI already installed"
          fi
          echo "âœ… GitHub CLI installation attempt complete"
          # Verify GitHub CLI installation - required for this action
          gh --version || { echo "ERROR: GitHub CLI verification failed. GitHub CLI is required for this action."; exit 1; }
        fi

    # Install GitHub CLI (Windows)
    - name: Install GitHub CLI (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo.
        echo ðŸ“¦ Installing GitHub CLI...

        rem Check if GitHub CLI is already installed
        where gh >nul 2>nul
        if %ERRORLEVEL% EQU 0 (
          echo âœ… GitHub CLI is already installed
          gh --version
          goto :verify
        ) else (
          echo Installing GitHub CLI via direct download...

          rem Download and install GitHub CLI
          curl -sSL https://github.com/cli/cli/releases/download/v2.74.2/gh_2.74.2_windows_amd64.msi -o gh.msi
          echo Installing GitHub CLI from MSI package...
          start /wait msiexec.exe /i gh.msi /quiet /norestart
          echo Waiting for installation to complete...
          timeout /t 5 /nobreak >nul
          del gh.msi

          rem Refresh PATH to include GitHub CLI installation directory
          echo Refreshing PATH to include GitHub CLI...

          rem Common installation paths for GitHub CLI
          set "GH_PATHS=C:\Program Files\GitHub CLI;C:\Program Files (x86)\GitHub CLI"

          rem Add GitHub CLI paths to current PATH
          set "PATH=%PATH%;%GH_PATHS%"

          rem Try to find gh.exe and add its directory to PATH if found
          for %%I in (gh.exe) do (
            if exist "%%~$PATH:I" (
              for %%J in ("%%~$PATH:I\.") do (
                echo Found gh.exe at: %%~dpJ
                set "PATH=%PATH%;%%~dpJ"
              )
            )
          )
        )

        echo âœ… GitHub CLI installation attempt complete

        :verify
        rem Verify GitHub CLI installation - required for this action
        where gh >nul 2>nul || (echo ERROR: GitHub CLI not found in PATH after installation. && exit /b 1)
        gh --version || (echo ERROR: GitHub CLI verification failed. GitHub CLI is required for this action. && exit /b 1)

    - name: Setup complete
      shell: bash
      run: |
        echo ""
        echo "âœ… Environment setup complete"
        echo ""

    # Run the main SmartFix analysis script with clear start/end markers - cross-platform compatible
    - name: Run Contrast AI SmartFix
      shell: bash
      run: |
        echo ""
        echo "================================================================"
        # Cross-platform compatible script execution
        if [ "${{ inputs.run_task }}" = "merge" ]; then
          echo "ðŸš€ STARTING CONTRAST AI SMARTFIX (Task: merge)"
          echo "================================================================"
          PYTHONPATH="${{ github.action_path }}" python "${{ github.action_path }}/src/merge_handler.py"
        elif [ "${{ inputs.run_task }}" = "closed" ]; then
          echo "ðŸš€ STARTING CONTRAST AI SMARTFIX (Task: closed)"
          echo "================================================================"
          PYTHONPATH="${{ github.action_path }}" python "${{ github.action_path }}/src/closed_handler.py"
        else
          echo "ðŸš€ STARTING CONTRAST AI SMARTFIX (Task: generate_fix)"
          echo "================================================================"
          PYTHONPATH="${{ github.action_path }}" python "${{ github.action_path }}/src/main.py"
        fi
        echo ""

        echo ""
        echo "================================================================"
        echo "âœ¨ CONTRAST AI SMARTFIX PROCESS COMPLETE"
        echo "================================================================"
      env:
        # --- Build Command ---
        BUILD_COMMAND: ${{ inputs.build_command }}
        # --- Max QA Intervention Attempts ---
        MAX_QA_ATTEMPTS: ${{ inputs.max_qa_attempts }}
        # --- Formatting Command ---
        FORMATTING_COMMAND: ${{ inputs.formatting_command }}
        # --- Max Open PRs ---
        MAX_OPEN_PRS: ${{ inputs.max_open_prs }}
        # --- GitHub Token ---
        GITHUB_TOKEN: ${{ inputs.github_token }}
        # --- Base Branch ---
        BASE_BRANCH: ${{ inputs.base_branch }}
        # --- Contrast API Credentials ---
        CONTRAST_HOST: ${{ inputs.contrast_host }}
        CONTRAST_ORG_ID: ${{ inputs.contrast_org_id }}
        CONTRAST_APP_ID: ${{ inputs.contrast_app_id }}
        CONTRAST_AUTHORIZATION_KEY: ${{ inputs.contrast_authorization_key }}
        CONTRAST_API_KEY: ${{ inputs.contrast_api_key }}
        # --- Google Gemini Credentials (LiteLLM) ---
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        # --- Anthropic Credentials (LiteLLM) ---
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        # --- AWS Bedrock API Bearer Token (LiteLLM) ---
        AWS_BEARER_TOKEN_BEDROCK: ${{ inputs.aws_bearer_token_bedrock }}
        AWS_REGION_NAME: ${{ inputs.aws_region }}
        # --- Azure Credentials for Azure OpenAI (LiteLLM) ---
        AZURE_API_KEY: ${{ inputs.azure_api_key }}
        AZURE_API_BASE: ${{ inputs.azure_api_base }}
        AZURE_API_VERSION: ${{ inputs.azure_api_version }}
        # --- Agent Configuration ---
        AGENT_MODEL: ${{ inputs.agent_model }}
        MAX_EVENTS_PER_AGENT: ${{ inputs.max_events_per_agent }}
        # --- Test Writing Configuration ---
        SKIP_WRITING_SECURITY_TEST: ${{ inputs.skip_writing_security_test }}
        # --- QA Configuration ---
        SKIP_QA_REVIEW: ${{ inputs.skip_qa_review }}
        # --- Debug Mode ---
        DEBUG_MODE: ${{ inputs.debug_mode }}
        # --- Vulnerability Configuration ---
        VULNERABILITY_SEVERITIES: ${{ inputs.vulnerability_severities }}
        # --- Run Task ---
        RUN_TASK: ${{ inputs.run_task }}
        # --- Telemetry Configuration ---
        ENABLE_FULL_TELEMETRY: ${{ inputs.enable_full_telemetry }}
        # --- Coding Agent ---
        CODING_AGENT: ${{ inputs.coding_agent }}
        # --- Use Contrast LLM ---
        USE_CONTRAST_LLM: ${{ inputs.use_contrast_llm }}
        # --- Anthropic Prompt Caching ---
        ENABLE_ANTHROPIC_PROMPT_CACHING: ${{ inputs.enable_anthropic_prompt_caching }}
